# Generated by Django 5.2.7 on 2026-04-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
    ]
